### PR TITLE
V2: improve performance, remove dependencies, code refactoring

### PR DESCRIPTION
**Pull request by danivek**
### Goals
- improve performance (add benchmark) #63 
- remove dependencies (lodash, joi) #63 
- code refactoring
- Keep same API as v1

### Breaking change
The only breaking change will be incompatibility with older version of Nodejs < 8

### Benchmark comparison
```bash
Platform info:
==============
Darwin 18.5.0 x64
Node.JS: 10.15.2
V8: 6.8.275.32-node.12
Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz × 8

Suite V1:
==============
serializeAsync x 5,154 ops/sec ±9.10% (72 runs sampled)
serialize x 28,150 ops/sec ±1.22% (86 runs sampled)
deserializeAsync x 49,116 ops/sec ±1.80% (81 runs sampled)
deserialize x 148,658 ops/sec ±1.26% (92 runs sampled)
serializeError x 281,786 ops/sec ±0.99% (90 runs sampled)
serializeError with a JSON API error object x 10,637 ops/sec ±2.82% (85 runs sampled)

Suite V2:
==============
serializeAsync x 64,411 ops/sec ±0.59% (82 runs sampled)
serialize x 150,408 ops/sec ±0.63% (93 runs sampled)
deserializeAsync x 111,881 ops/sec ±0.31% (84 runs sampled)
deserialize x 445,711 ops/sec ±0.29% (94 runs sampled)
serializeError x 294,273 ops/sec ±0.79% (90 runs sampled)
serializeError with a JSON API error object x 16,864,514 ops/sec ±0.32% (93 runs sampled)
```

### CODE REVIEW

**Comment by danivek** [comment]
@mattiloh, I try an other implementation of non blocking (de)serialization (removing usage of stream) to improve performance. You can see it here: https://github.com/danivek/json-api-serializer/blob/v2/lib/JSONAPISerializer.js#L325. All tests are passing.

Do you see any issue with this implementation ?

**Comment by mattiloh** [comment]
Wow! Really great performance improvements 🚀 
Is it coming from the usage of `Map` instead of an array for `included`? 🤔

Sure, I'm fine with using `setImmediate` instead of streams. Unfortunately, it's still not working in browsers with it, since `setImmediate` seems [not to be really widely supported](https://caniuse.com/#feat=setimmediate) yet. But I guess it's a step in the right direction.

**Comment by danivek** [comment]
Yes a little bit, but the real performance gain comes from the use of native functions rather than lodash ones + some code optimization.

Of course this library still not work on browsers because of `setImmediate`. Maybe we need to fallback to `setTimeout` or use polyfill to make it work.

**Comment by johannesschobel** [comment]
Hey @danivek , good to see the improvements.. nice work on the performance!
May I add another feature request for the upcoming version? I would really (!!!) love to see "official typescript" definitions. Maybe you can add those as well?

Thank you very much in advance!

**Comment by mattiloh** [comment]
> Of course this library still not work on browsers because of setImmediate. Maybe we need to fallback to setTimeout or use polyfill to make it work.

So far, I didn't need it in the browser, so no hard feelings from my side 😉 
But I think it has been requested sometimes. If `setImmediate` is the only problem for browser-support, we could also think about adding a section to the README to explain how it could be used with a `setImmediate` polyfill.
Anyhow, I would suggest to tackle browser support in a separate PR (if it's really needed).

**Comment by johannesschobel** [comment]
Hey @danivek ,

i would like to propse another feature request.. 
What do you think about implementing something like "Transformers" known from `Fractal` (php package for transforming & serializing data into various formats).
https://fractal.thephpleague.com/

Using Transformers would allow for:
1) easy rename properties: because they take the part of "mapping" from one structure to another one
2) allow for computed properties: because you would be able to add new properties to this transformer
3) convert types: e.g., you would be able to convert values to a proper type (e.g., the `id` **must** be a string)
4) ...

What do you think about this?
All the best

**Comment by danivek** [comment]
I think we should avoid introducing a new kind of domain-specific language (DSL) in this library. `json-api-serializer` is only responsible to (de)serialize a data to JSON API compliant responses. If you want to transform your data, you should do it before using this library.

The only possible option we could add for this library, is a `transform` option, that will act as a hook before (de)serializing attributes. So you will be able to use any kind of library you want to transform attributes.

**Comment by johannesschobel** [comment]
thanks for your response @danivek ... i think, a hook to transform the data would be nice.. Any idea how this would / could look like? Would it be be possible to just call a method and pass the current object?

Like this:
```
// user.transformer.ts
class UserTransformer extends Transformer() {
  transform(entity: User): UserResponse {
    return {
      id: String(entity.id),
      firstName: entity.firstname,
      // ...
      name: entity.firstname + ' ' + entity.lastname,
    }
  }
}
```

What do you think?

**Pull request merged**
