### PR TITLE
Enhancement: reduce errors generated from JSDoc expectations

### PR DESCRIPTION
**Pull request by igneel64**
**Current state:**
Currently some minor typos etc are generating couple of warnings/errors when checking compliance with JSDoc.

**Changes introduced:**
Fix documentation for function definitions that would generate these errors.

### CODE REVIEW

**Comment by danivek** [comment]
Thanks @igneel64 !

Maybe we can add eslint-plugin-jsdoc[eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc) to enforce jsdoc consistency.

What do you think about it ?

**Comment by igneel64** [comment]
@danivek  Happy to contribute!
Really great that you came up with this plugin, didn't even know it myself! 
Checked it up and I think the `recommended` rules will be just fine and will promote consistency for the project.

I will add the plugin, make the required changes and come back to you.

**Comment by igneel64** [comment]
@danivek Ready for your review.

**Comment by danivek** [comment]
Wow, I would not have been so far on adding jsdoc when it was missing. 👍 

Big thanks ! @igneel64

**Pull request merged**
