### PR TITLE
Fix for missing 'path' in _get in serializeMixedData()

### PR DESCRIPTION
**Pull request by stefanvanherwijnen**

### CODE REVIEW

**Comment by stefanvanherwijnen** [comment]
Maybe the default value (third argument) should be removed to pass the test.

**Comment by stefanvanherwijnen** [comment]
Actually, I am not sure if type should be set to ```data.type```or to ```typeOption.type```. In the latter case ```_get``` can be omitted.

**Comment by danivek** [comment]
I don't understand why you need to hard code the path with 'type'.

On Readme https://github.com/danivek/json-api-serializer#serialize-1 the option for type accept a string for the path to the key to use to determine type or a function deriving a type-string from each data-item.

So you should always have a string path for `typeOption.type`

**Comment by stefanvanherwijnen** [comment]
... You are right. I confused this ```type``` key with the ```type```key on a relationship.
Maybe it is more clear to rename ```type``` in typeConfig to ```typeKey```? (as that is what it really is, the string for the path to the key, as clearly stated in the docs, which I apparently did not read well enough :expressionless: )

**Pull request closed without merging**
